from __future__ import annotations

from typing import Protocol, runtime_checkable

from qts.backtest.orders import OrderRequest


@runtime_checkable
class BrokerAdapter(Protocol):
    def submit_order(self, order: OrderRequest) -> object: ...

    def cancel_order(self, order_id: str) -> None: ...

    def get_order_status(self, order_id: str) -> object: ...

    def get_open_orders(self) -> list[object]: ...

    def get_positions(self) -> list[object]: ...

    def get_account(self) -> object: ...

    def get_cash(self) -> float: ...

    def get_clock(self) -> object: ...
